runtime: php81

env_variables:
  APP_ENV: development
  APP_KEY: base64:TneqExDgMWcDP2mM/caSugJqZsbDa6wCSpAtow1/zAM=
  DB_CONNECTION: mysql
  DB_HOST=34.101.197.37
  DB_PORT=3306
  DB_DATABASE=tangsimekar
  DB_USERNAME=root
  DB_PASSWORD=

handlers:
  - url: /static
    static_dir: public/
  - url: /(.*
    script: auto
